### ISSUE TITLE
学长好！请问你有意愿加入Open-BJUT民间组织吗？

### ISSUE THREAD

**Issue by Nagi-ovo** [zy19970/BJUT-PPT-template#1]
刚建立的BJUT开源组织，详情可见[组织链接](https://github.com/Open-BJUT)
我们诚挚地邀请你加入我们，你不需要投入什么精力和时间，只是可以让你精心制作的ppt模板被更多人看到、用到，帮助到更多工大学子！

**Comment by zy19970** [comment]
可以联系邮箱：zy19970@emails.bjut.edu.cn
